version: '3'

tasks:
  default:
    desc: Liste les tâches disponibles
    cmds:
      - task --list
    silent: true

  day-1:
    desc: Lance la séance 1 (diaporama + notes synchronisées)
    dir: cours/presentations
    cmds:
      - npm run day-1 -- {{.CLI_ARGS}}

  themes:
    desc: Lance la présentation des trois projets (diaporama + notes synchronisées)
    dir: cours/presentations
    cmds:
      - npm run themes -- {{.CLI_ARGS}}
